defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 16

development:
  <<: *defaults
  database: stripeon_development

test:
  <<: *defaults
  database: stripeon_test

production:
  <<: *defaults
  database: stripeon_production
